### ISSUE TITLE
Automate templating out and updating of the docker image READMEs

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#1439]
Now we manually update the descriptions on Docker Hub for the published container images, which is annoying and error prone (easy to forget).

It would be nice if we could provide a template for this which is templated out with the release tags/supported versions and updated automatically after image push through Github Actions.

From Stack Overflow:

```
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        DOCKERHUB_REPOSITORY: peterevans/dockerhub-description
```
(https://stackoverflow.com/a/57671247)
