### ISSUE TITLE
Unreadable text in translation view 

### ISSUE THREAD

**Issue by CharString** [open-formulieren/open-forms#3582]
This rule from bootstrap sets a background-color without specifying a foreground-color. This results in near-white on near-white in dark mode.

```css
.form-control:disabled, .form-control[readonly] {
  background-color: #e9ecef;
  opacity: 1;
}
```
![image](https://github.com/open-formulieren/formio-builder/assets/325643/5848fb85-7347-4ca0-b0b8-be37118b4350)
